### PR TITLE
the aiting.md file has been added

### PR DESCRIPTION
**Pull request by zhou0248**
add aiting.md file to this repo

### CODE REVIEW

**Review by prof3ssorSt3v3 — COMMENTED** [review]
hi there. Nice markdown

**Review by prof3ssorSt3v3 — CHANGES_REQUESTED** [review]
You need some text with the heading, not just a #

**Comment by zhou0248** [comment]
md file has been updated

**Review by prof3ssorSt3v3 — APPROVED** [review]
Great work.

**Pull request merged**
